### ISSUE TITLE
Dockerize app and possibly add k8s support

### ISSUE THREAD

**Issue by panagiotisbellias** [jcilacad/aeroplanner-rest-api#102]
After these are completed:
- [ ] #23 
- [x] #27 
- [x] #85 
- [ ] #96 
- [x] #97 
- [x] #99 
- [ ] #100 

Dockerize project and if wanted add k8s support

Note: check before refactoring for the latest changes and future developments and review what is still needed

**Comment by panagiotisbellias** [comment]
Please follow the README.md instructions for pushing the image in github container registry. The purpose is that the image will be available from the 'Packages' section of repository

**Comment by panagiotisbellias** [comment]
Planned Actions:

- [ ] Waiting for #101 related actions
- [ ] Adding k8s configuration files and instructions for a microK8S installation

PS: Nice work with the available container package

**Comment by panagiotisbellias** [comment]
Proposal:

I suggest to close this issue for now as kubernetes configuration could also be done in next release

**Comment by jcilacad** [comment]
Done
