### ISSUE TITLE
Prepare for release v1.0.0

### ISSUE THREAD

**Issue by panagiotisbellias** [jcilacad/aeroplanner-rest-api#103]
After these are completed:
- [x] #23 
- [x] #27 
- [x] #85 
- [x] #97 
- [x] #99 
- [x] #101 
- [x] #102 

Refactor project's version to 1.0.0, make github release with assets and release notes and possibly integrate github actions workflows to update dependencies, test them and increase the minor versions automatically

Note: check before refactoring for the latest changes and future developments

**Comment by panagiotisbellias** [comment]
@jcilacad please review the current GitHub issues and inform about starting the release process which is:
- setting application's version to v1.0.0
- creating branch release/v1.0.0 and tag v1.0.0
- creating GitHub release v1.0.0 with assets the built jar file and release notes describing what is developed
- adding CHANGELOG.md in root dir
- deploying artifact in maven repository if applicable and needed
- make a new issue about next release (possibly v1.1.0) to embed all the remaining open issues and future ones
- return to main branch check-outing it and merging release/v1.0.0

**Comment by jcilacad** [comment]
I think we can start the release for v1.0.0
