### ISSUE TITLE
Use Redis for caching the requests

### ISSUE THREAD

**Issue by panagiotisbellias** [jcilacad/aeroplanner-rest-api#109]
After:
- [x] #99 
- [ ] #100 
- [x] #101 
- [x] #102 

use redis server to cache the requests and responses

Note: check before refactoring for the latest changes and future developments and review what is still needed

**Comment by panagiotisbellias** [comment]
In my opinion it can be removed from this release (v1.0.0)

**Comment by jcilacad** [comment]
I’ll go ahead and close this issue now.

**Comment by panagiotisbellias** [comment]
I suggest that this should be reopened for the next release, I'm just removing it from release-v1.0.0 task's description
