### ISSUE TITLE
Write unit and integration tests.

### ISSUE THREAD

**Issue by jcilacad** [jcilacad/aeroplanner-rest-api#23]

**Comment by panagiotisbellias** [comment]
Hello,
I really liked and like to contribute to this project and I'll keep an eye to inform unit tests according to new developments and merges, so even if integration tests are implemented the issue can't be closed but only as the last one. As for the integration tests I leave some placeholder test classes with rest assured library if wanted and needed in order for someone else to implement them as I'm not an expert for this.

Thanks,
Panagiotis

**Comment by jcilacad** [comment]
@panagiotisbellias 
Thanks for your input and efforts on the unit tests. Your contributions are appreciated.

**Comment by panagiotisbellias** [comment]
@jcilacad Can you tell me how you run the new integration tests in order to automate their execution in CI workflow?

**Comment by jcilacad** [comment]
@panagiotisbellias The mvn command to run the integration tests is `mvn failsafe:integration-test`.

**Comment by jcilacad** [comment]
Utilize TestConstants class for integration testing.

**Comment by jcilacad** [comment]
> @panagiotisbellias The mvn command to run the integration tests is `mvn failsafe:integration-test`.

@panagiotisbellias I forgot to mention, for it to work, the Docker service must also be running.

**Comment by jcilacad** [comment]
Nice

**Comment by panagiotisbellias** [comment]
I think this can be closed since test execution is automated
