### ISSUE TITLE
Merge common code

### ISSUE THREAD

**Issue by panagiotisbellias** [jcilacad/aeroplanner-rest-api#97]
After these are completed:
- [ ] #23 
- [x] #27 
- [x] #85 
- [ ] #96 

consider these:
- [x] combine AdminSeeder class and RoleSeeder class to one
- [x] extract common code in GlobalExceptionHandler

Note: check before refactoring for the latest changes and future developments and review what and if it is still needed

**Comment by panagiotisbellias** [comment]
@jcilacad Review my suggestion please and assign this issue to me if you agree or close it as not planned in case there is no need for that

Thanks

**Comment by jcilacad** [comment]
@panagiotisbellias  go for it.

**Comment by panagiotisbellias** [comment]
Done
